### ISSUE TITLE
Roadmap for release v1

### ISSUE THREAD

**Issue by kabachook** [yandex-cloud/cq-source-yc#39]
- [ ] Migrate to plugin-sdk v4
- [ ] Enable internal repo sync
- [ ] Tests (`client/` and `resources/`)
- [ ] Docs
       - Minimal role – `auditor` + research if additional viewer roles are required
- [ ] CloudQuery Hub releases via Actions
- [ ] -----✂️First release here✂️-----
- [ ] Changelog bot (?)

**Comment by toufreach5** [comment]
Hello @kabachook,

What is missing for the v1.0.0 release ?

BR

**Comment by kabachook** [comment]
@toufreach5 Released https://github.com/yandex-cloud/cq-source-yc/releases/tag/v1.0.0

**Comment by toufreach5** [comment]
Thanks @kabachook
